# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
# how to find the memory size of any array
memory_size = arr.nbytes
memory_size

80

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
array1 = np.zeros(10)
array1[4]=1
array1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
A = np.arange(start=10, stop=50)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
A[-1]=10
A[0]=49
A

array([49, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
B = np.arange(9).reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
array1 = np.array([1,2,0,0,4,0])
array2 = array1[array1>0]
array2

array([1, 2, 4])

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [10]:
array_eye = np.eye(3,3)
array_identity = np.identity(3)

print(array_eye)
print(array_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [11]:
np.random.random((3,3,3))

array([[[0.30949285, 0.71801451, 0.74407003],
        [0.57495529, 0.44825699, 0.55412579],
        [0.64407183, 0.59853377, 0.65243184]],

       [[0.49111733, 0.27374508, 0.62458615],
        [0.69513812, 0.81114528, 0.96647765],
        [0.18043355, 0.91110114, 0.3267039 ]],

       [[0.07075652, 0.39304992, 0.78258178],
        [0.76089195, 0.38407679, 0.21792762],
        [0.68994689, 0.77097696, 0.10765273]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [12]:
array_random = np.random.random((10,10))
print(array_random)
print(array_random.min())
print(array_random.max())

[[0.4473676  0.09878402 0.5471442  0.8112705  0.82137066 0.12345751
  0.25134858 0.45441986 0.58521286 0.11566859]
 [0.41719207 0.15677875 0.8279415  0.03232896 0.16756035 0.56574547
  0.13959869 0.92835229 0.18583083 0.6828559 ]
 [0.46400984 0.72733234 0.24919405 0.60217524 0.17532483 0.62962106
  0.3038525  0.94702971 0.93838407 0.40433825]
 [0.1850195  0.47467355 0.18624356 0.84589003 0.9752545  0.2775474
  0.10694593 0.90454024 0.22624012 0.0368788 ]
 [0.17803921 0.20950134 0.79836168 0.02498126 0.36188792 0.65570164
  0.07961308 0.07821557 0.69477315 0.56784064]
 [0.64011721 0.57224394 0.64247285 0.57439911 0.72741631 0.12215073
  0.03327047 0.66275487 0.945428   0.29384191]
 [0.0581262  0.87657428 0.1202106  0.31132554 0.74047668 0.59140394
  0.77914321 0.56348831 0.45076927 0.545462  ]
 [0.99189891 0.0335644  0.39397126 0.08530316 0.00330892 0.91412495
  0.39101552 0.28112101 0.73849031 0.2458883 ]
 [0.046219   0.54063608 0.08362846 0.73236357 0.67105171 0.24564627
  0.60513319 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [13]:
array_random2 = np.random.random(30)
print(array_random2)
print(array_random2.mean())

[0.05716618 0.67539223 0.74777766 0.80764397 0.87285526 0.64836085
 0.38725332 0.42295396 0.44037011 0.11319925 0.82443705 0.28871811
 0.38587926 0.79062179 0.42436878 0.04571741 0.2416719  0.54981924
 0.23804221 0.08027601 0.2390226  0.30592278 0.56499578 0.49307201
 0.22265074 0.02718308 0.658788   0.39379867 0.55404846 0.97334286]
0.44917831683573906


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
array2d = np.ones((5,5))
array2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
array2d[1:-1,1:-1] = 0
array2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [16]:
array1 = np.zeros((5,5))
array1[1,0]=1
array1[2,:2]=2
array1[3,:3]=3
array1[-1,:-1]=4
print(array1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 2. 0. 0. 0.]
 [3. 3. 3. 0. 0.]
 [4. 4. 4. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
checkerboard = np.zeros((8,8), dtype = int)
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [18]:
np.unravel_index(100, (6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [21]:
array1 = np.random.random((5,5))
array1_mean = array1.mean()
array1_std = array1.std()
array_Z = (array1 - array1_mean)/array1_std

print(array_Z)

[[ 1.55568219 -1.31045484  0.64499983 -1.12834181 -0.46006993]
 [ 1.57511155  0.49667768 -0.99721111  1.23525515 -0.45682593]
 [ 0.94270501 -1.50329505  0.30123941 -1.30287911  0.06162411]
 [-0.82774078 -1.2570042   0.89409722 -0.72422779 -1.13252822]
 [ 0.56371105  1.63218122  0.02343937  0.48349191  0.69036305]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [27]:
color = np.dtype([('R', np.ubyte),
                  ('G', np.ubyte),
                  ('B', np.ubyte),
                  ('A', np.ubyte)])

print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
