In [2]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [7]:
A = np.random.random((5,3))
B = np.random.random((3,2))

A@B

array([[0.23888359, 0.52016478],
       [0.40878014, 0.74447088],
       [0.55070774, 1.16520472],
       [0.53929239, 1.19014095],
       [0.46319707, 1.02104181]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [19]:
A = np.arange(0,10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
A[(A>3)&(A<8)] *= -1

In [21]:
A

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
#numpy 후의 -1은 축의 개념

9

10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z**Z      <-legal

2 << Z >> 2 <- legal

Z <- Z    <-illegal

1j*Z      < legal

Z/1/1    <- legal

Z<Z>Z     <- illegal


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [45]:
np.array(0)/ np.array(0)

/tmp/ipykernel_971/4140018299.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0)/ np.array(0)


np.float64(nan)

In [46]:
np.array(0)//np.array(0)

/tmp/ipykernel_971/3350367291.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)//np.array(0)


np.int64(0)

In [47]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_971/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

nan

0  

-9.22337204e+18

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [51]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)

[6 5 3 3 9 3 3 8 5 1]
[3 8 0 0 2 7 3 8 3 8]


In [52]:
np.intersect1d(Z1,Z2)

array([3, 8])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [53]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_971/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [55]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [22]:
A = np.random.rand(5)
B = np.random.rand(5)

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(B, A, out=A)

print(A)

[-0.18249346 -0.26965518 -0.1276613  -0.00370958 -0.12683267]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [25]:
arr = np.random.uniform(0,10,10)
print(arr)
print(arr//1)   #몫
print(arr - arr%1)  # 소수부분 제거

[2.58628625 9.36183168 7.52650372 8.61559607 4.42219172 9.77324163
 1.75483085 6.45405849 5.28495033 9.18197845]
[2. 9. 7. 8. 4. 9. 1. 6. 5. 9.]
[2. 9. 7. 8. 4. 9. 1. 6. 5. 9.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [43]:
A = np.arange(5)
B = A + np.zeros((5,5))
print(B)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [41]:
C = np.random.random(10)
D = np.sort(C)
print(D)

[0.09150571 0.09220209 0.09678291 0.21040756 0.31638009 0.43634701
 0.6263688  0.76553278 0.82878593 0.96716456]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [35]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [58]:
A = np.random.random((10,2))
X,Y = A[:,0],A[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)

print(R)
print(T)

[0.19636745 0.8972777  0.82671184 0.72796331 0.36844017 1.13167583
 0.15633669 0.70167351 0.3348191  1.0560231 ]
[0.14486847 1.13725662 0.67582054 1.42261033 0.9466569  0.51884125
 0.75474152 1.40299828 0.54440682 0.75299953]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [60]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([0.4341329 , 0.43833782, 0.85981191, 0.        , 0.48982479,
       0.28032913, 0.73358032, 0.78995912, 0.20763543, 0.55213391])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [61]:
Z = np.arange(100)
v = np.random.uniform(0,100)
min = Z[np.abs(Z-v).argmin()]
min

np.int64(23)

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [62]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):   #np.ndenumerate()는 numpy 배열을 순회하면서 (index,값)을 반환하는 함수
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [63]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),1)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [65]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[7 8 0]
 [5 8 5]
 [2 4 7]]
[[2 4 7]
 [5 8 5]
 [7 8 0]]


In [66]:
Z= np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 7 7]
 [2 9 3]
 [6 6 2]]
[[6 6 2]
 [5 7 7]
 [2 9 3]]


In [67]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[6 4 1]
 [5 2 0]
 [8 2 5]]
[[5 2 0]
 [6 4 1]
 [8 2 5]]
